baseURL = 'https://diogoqueiroz.page/'
languageCode = 'en-us'
title = 'Diogo Queiroz | Blog'
theme = 'hugo-coder'

publishDir = '../html/'

[permalinks]
  posts = "blog/posts/:title/"

[params]

  env = 'production'
  defaultTheme = 'dark'
  disableThemeToggle = false

  [params.homeInfoParams]
    Title = 'Welcome to my blog'
    Content = 'Tech articles based on my own projects'

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

